// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountTemplatesForTeam(ctx context.Context, owningTeamID pgtype.UUID) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Draft-only delete. The releases.template_version_id FK is ON DELETE RESTRICT,
	// so deleting a non-draft version that any release references would fail at
	// the DB level. We gate at the query level as a fast-path + clear error
	// shape: returns zero rows when the version is not draft so the handler can
	// return 409 instead of a generic DB error.
	DeleteDraftTemplateVersion(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	// Retention: an expired session is already unusable (GetSession filters on
	// expires_at), so the row is nothing but an encrypted id_token and refresh
	// token we no longer need. Sweep them instead of keeping them forever — the
	// s_expires_at index makes this cheap. Deletes in bounded batches so one call
	// can never hold a long lock on a table that logins are writing to.
	//
	// ORDER BY + FOR UPDATE SKIP LOCKED makes concurrent sweepers actually safe
	// rather than merely idempotent: two replicas take disjoint batches in the
	// same order instead of racing for the same rows, so neither deadlocks and
	// neither comes back short while work remains (which the caller reads as
	// "nothing left" and would otherwise end the pass early).
	// The batch must be a CTE, not an IN (SELECT ... LIMIT). Postgres plans the
	// latter as a semi-join and re-executes the subquery per outer row; with
	// SKIP LOCKED each re-execution returns a *different* row, so the DELETE
	// removes more than batch_size (EXPLAIN shows Nested Loop Semi Join over the
	// Limit node). A CTE carrying a locking clause is never inlined, so it is
	// evaluated exactly once.
	DeleteExpiredSessions(ctx context.Context, batchSize int32) (int64, error)
	DeleteRelease(ctx context.Context, id pgtype.UUID) error
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteTeam(ctx context.Context, id pgtype.UUID) error
	DeleteTeamMembership(ctx context.Context, arg DeleteTeamMembershipParams) error
	GetClusterByName(ctx context.Context, name string) (Cluster, error)
	GetReleaseByID(ctx context.Context, id pgtype.UUID) (GetReleaseByIDRow, error)
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetTeamByID(ctx context.Context, id pgtype.UUID) (Team, error)
	GetTeamByName(ctx context.Context, name string) (Team, error)
	GetTeamMembership(ctx context.Context, arg GetTeamMembershipParams) (TeamMembership, error)
	GetTemplateByName(ctx context.Context, name string) (GetTemplateByNameRow, error)
	GetTemplateVersion(ctx context.Context, arg GetTemplateVersionParams) (TemplateVersion, error)
	GetTemplateVersionByID(ctx context.Context, id pgtype.UUID) (TemplateVersion, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByOidcSubject(ctx context.Context, oidcSubject string) (User, error)
	InsertCluster(ctx context.Context, arg InsertClusterParams) (Cluster, error)
	InsertRelease(ctx context.Context, arg InsertReleaseParams) (Release, error)
	InsertTeam(ctx context.Context, arg InsertTeamParams) (Team, error)
	InsertTeamMembership(ctx context.Context, arg InsertTeamMembershipParams) (TeamMembership, error)
	InsertTemplate(ctx context.Context, arg InsertTemplateParams) (Template, error)
	InsertTemplateV2(ctx context.Context, arg InsertTemplateV2Params) (Template, error)
	InsertTemplateVersion(ctx context.Context, arg InsertTemplateVersionParams) (TemplateVersion, error)
	InsertTemplateVersionV2(ctx context.Context, arg InsertTemplateVersionV2Params) (TemplateVersion, error)
	ListAllReleases(ctx context.Context, arg ListAllReleasesParams) ([]ListAllReleasesRow, error)
	ListClusters(ctx context.Context) ([]Cluster, error)
	// Releases created by any user whose email is in the demo domain ($1, e.g.
	// "demo.kubeport"). Backs the scoped admin view for demo accounts: a demo
	// admin sees the demo user's releases but nothing from real users.
	ListReleasesForDemoDomain(ctx context.Context, arg ListReleasesForDemoDomainParams) ([]ListReleasesForDemoDomainRow, error)
	ListReleasesForUser(ctx context.Context, arg ListReleasesForUserParams) ([]ListReleasesForUserRow, error)
	ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListTeamsForUser(ctx context.Context, userID pgtype.UUID) ([]Team, error)
	ListTemplateVersions(ctx context.Context, name string) ([]TemplateVersion, error)
	ListTemplates(ctx context.Context) ([]ListTemplatesRow, error)
	NextTemplateVersion(ctx context.Context, templateID pgtype.UUID) (int32, error)
	PublishTemplateVersion(ctx context.Context, id pgtype.UUID) (TemplateVersion, error)
	SetTemplateVersionStatus(ctx context.Context, arg SetTemplateVersionStatusParams) (TemplateVersion, error)
	// Draft-only update. Published/deprecated versions are immutable so we gate on
	// status = 'draft' in the WHERE clause. Callers distinguish "not found" from
	// "not draft" by reading the version first; the UPDATE returns zero rows when
	// the gate fails. Content columns are optional (sqlc.narg) so callers only
	// send what changed. authoring_mode is intentionally not patchable — drafts
	// keep the mode they were created with.
	UpdateDraftTemplateVersion(ctx context.Context, arg UpdateDraftTemplateVersionParams) (TemplateVersion, error)
	UpdateReleaseValuesAndVersion(ctx context.Context, arg UpdateReleaseValuesAndVersionParams) error
	UpdateSessionTokens(ctx context.Context, arg UpdateSessionTokensParams) error
	UpdateTemplateCurrentVersion(ctx context.Context, arg UpdateTemplateCurrentVersionParams) error
	UpdateTemplateMeta(ctx context.Context, arg UpdateTemplateMetaParams) (Template, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
