// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRelease = `-- name: DeleteRelease :exec
DELETE FROM releases WHERE id = $1
`

func (q *Queries) DeleteRelease(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRelease, id)
	return err
}

const getReleaseByID = `-- name: GetReleaseByID :one
SELECT r.id, r.name, r.template_version_id, r.cluster_id, r.namespace, r.values_json, r.rendered_yaml, r.created_by_user_id, r.created_at, r.updated_at, c.name AS cluster_name, c.api_url AS cluster_api_url, c.ca_bundle AS cluster_ca_bundle,
       t.name AS template_name, tv.version AS template_version, tv.ui_spec_yaml
  FROM releases r
  JOIN clusters c          ON c.id = r.cluster_id
  JOIN template_versions tv ON tv.id = r.template_version_id
  JOIN templates t         ON t.id = tv.template_id
 WHERE r.id = $1
`

type GetReleaseByIDRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	TemplateVersionID pgtype.UUID        `json:"template_version_id"`
	ClusterID         pgtype.UUID        `json:"cluster_id"`
	Namespace         string             `json:"namespace"`
	ValuesJson        json.RawMessage    `json:"values_json"`
	RenderedYaml      string             `json:"rendered_yaml"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ClusterName       string             `json:"cluster_name"`
	ClusterApiUrl     string             `json:"cluster_api_url"`
	ClusterCaBundle   pgtype.Text        `json:"cluster_ca_bundle"`
	TemplateName      string             `json:"template_name"`
	TemplateVersion   int32              `json:"template_version"`
	UiSpecYaml        string             `json:"ui_spec_yaml"`
}

func (q *Queries) GetReleaseByID(ctx context.Context, id pgtype.UUID) (GetReleaseByIDRow, error) {
	row := q.db.QueryRow(ctx, getReleaseByID, id)
	var i GetReleaseByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TemplateVersionID,
		&i.ClusterID,
		&i.Namespace,
		&i.ValuesJson,
		&i.RenderedYaml,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClusterName,
		&i.ClusterApiUrl,
		&i.ClusterCaBundle,
		&i.TemplateName,
		&i.TemplateVersion,
		&i.UiSpecYaml,
	)
	return i, err
}

const insertRelease = `-- name: InsertRelease :one
INSERT INTO releases (name, template_version_id, cluster_id, namespace, values_json, rendered_yaml, created_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, template_version_id, cluster_id, namespace, values_json, rendered_yaml, created_by_user_id, created_at, updated_at
`

type InsertReleaseParams struct {
	Name              string          `json:"name"`
	TemplateVersionID pgtype.UUID     `json:"template_version_id"`
	ClusterID         pgtype.UUID     `json:"cluster_id"`
	Namespace         string          `json:"namespace"`
	ValuesJson        json.RawMessage `json:"values_json"`
	RenderedYaml      string          `json:"rendered_yaml"`
	CreatedByUserID   pgtype.UUID     `json:"created_by_user_id"`
}

func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, insertRelease,
		arg.Name,
		arg.TemplateVersionID,
		arg.ClusterID,
		arg.Namespace,
		arg.ValuesJson,
		arg.RenderedYaml,
		arg.CreatedByUserID,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TemplateVersionID,
		&i.ClusterID,
		&i.Namespace,
		&i.ValuesJson,
		&i.RenderedYaml,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllReleases = `-- name: ListAllReleases :many
SELECT r.id, r.name, r.template_version_id, r.cluster_id, r.namespace,
       r.created_by_user_id, r.created_at, r.updated_at,
       c.name AS cluster_name, t.name AS template_name, tv.version AS template_version
  FROM releases r
  JOIN clusters c          ON c.id = r.cluster_id
  JOIN template_versions tv ON tv.id = r.template_version_id
  JOIN templates t         ON t.id = tv.template_id
 WHERE ($1::text IS NULL OR c.name = $1)
   AND ($2::text IS NULL OR r.namespace = $2)
   AND ($3::text IS NULL OR t.name = $3)
 ORDER BY r.created_at DESC
 LIMIT $5::int OFFSET $4::int
`

type ListAllReleasesParams struct {
	Cluster   pgtype.Text `json:"cluster"`
	Namespace pgtype.Text `json:"namespace"`
	Template  pgtype.Text `json:"template"`
	Off       int32       `json:"off"`
	Lim       int32       `json:"lim"`
}

type ListAllReleasesRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	TemplateVersionID pgtype.UUID        `json:"template_version_id"`
	ClusterID         pgtype.UUID        `json:"cluster_id"`
	Namespace         string             `json:"namespace"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ClusterName       string             `json:"cluster_name"`
	TemplateName      string             `json:"template_name"`
	TemplateVersion   int32              `json:"template_version"`
}

func (q *Queries) ListAllReleases(ctx context.Context, arg ListAllReleasesParams) ([]ListAllReleasesRow, error) {
	rows, err := q.db.Query(ctx, listAllReleases,
		arg.Cluster,
		arg.Namespace,
		arg.Template,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllReleasesRow
	for rows.Next() {
		var i ListAllReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TemplateVersionID,
			&i.ClusterID,
			&i.Namespace,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClusterName,
			&i.TemplateName,
			&i.TemplateVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesForDemoDomain = `-- name: ListReleasesForDemoDomain :many
SELECT r.id, r.name, r.template_version_id, r.cluster_id, r.namespace,
       r.created_by_user_id, r.created_at, r.updated_at,
       c.name AS cluster_name, t.name AS template_name, tv.version AS template_version
  FROM releases r
  JOIN clusters c          ON c.id = r.cluster_id
  JOIN template_versions tv ON tv.id = r.template_version_id
  JOIN templates t         ON t.id = tv.template_id
  JOIN users u             ON u.id = r.created_by_user_id
 WHERE u.email ILIKE '%@' || $1::text
   AND ($2::text IS NULL OR c.name = $2)
   AND ($3::text IS NULL OR r.namespace = $3)
   AND ($4::text IS NULL OR t.name = $4)
 ORDER BY r.created_at DESC
 LIMIT $6::int OFFSET $5::int
`

type ListReleasesForDemoDomainParams struct {
	Domain    string      `json:"domain"`
	Cluster   pgtype.Text `json:"cluster"`
	Namespace pgtype.Text `json:"namespace"`
	Template  pgtype.Text `json:"template"`
	Off       int32       `json:"off"`
	Lim       int32       `json:"lim"`
}

type ListReleasesForDemoDomainRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	TemplateVersionID pgtype.UUID        `json:"template_version_id"`
	ClusterID         pgtype.UUID        `json:"cluster_id"`
	Namespace         string             `json:"namespace"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ClusterName       string             `json:"cluster_name"`
	TemplateName      string             `json:"template_name"`
	TemplateVersion   int32              `json:"template_version"`
}

// Releases created by any user whose email is in the demo domain ($1, e.g.
// "demo.kubeport"). Backs the scoped admin view for demo accounts: a demo
// admin sees the demo user's releases but nothing from real users.
func (q *Queries) ListReleasesForDemoDomain(ctx context.Context, arg ListReleasesForDemoDomainParams) ([]ListReleasesForDemoDomainRow, error) {
	rows, err := q.db.Query(ctx, listReleasesForDemoDomain,
		arg.Domain,
		arg.Cluster,
		arg.Namespace,
		arg.Template,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReleasesForDemoDomainRow
	for rows.Next() {
		var i ListReleasesForDemoDomainRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TemplateVersionID,
			&i.ClusterID,
			&i.Namespace,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClusterName,
			&i.TemplateName,
			&i.TemplateVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesForUser = `-- name: ListReleasesForUser :many
SELECT r.id, r.name, r.template_version_id, r.cluster_id, r.namespace,
       r.created_by_user_id, r.created_at, r.updated_at,
       c.name AS cluster_name, t.name AS template_name, tv.version AS template_version
  FROM releases r
  JOIN clusters c          ON c.id = r.cluster_id
  JOIN template_versions tv ON tv.id = r.template_version_id
  JOIN templates t         ON t.id = tv.template_id
 WHERE r.created_by_user_id = $1
   AND ($2::text IS NULL OR c.name = $2)
   AND ($3::text IS NULL OR r.namespace = $3)
   AND ($4::text IS NULL OR t.name = $4)
 ORDER BY r.created_at DESC
 LIMIT $6::int OFFSET $5::int
`

type ListReleasesForUserParams struct {
	CreatedByUserID pgtype.UUID `json:"created_by_user_id"`
	Cluster         pgtype.Text `json:"cluster"`
	Namespace       pgtype.Text `json:"namespace"`
	Template        pgtype.Text `json:"template"`
	Off             int32       `json:"off"`
	Lim             int32       `json:"lim"`
}

type ListReleasesForUserRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	TemplateVersionID pgtype.UUID        `json:"template_version_id"`
	ClusterID         pgtype.UUID        `json:"cluster_id"`
	Namespace         string             `json:"namespace"`
	CreatedByUserID   pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ClusterName       string             `json:"cluster_name"`
	TemplateName      string             `json:"template_name"`
	TemplateVersion   int32              `json:"template_version"`
}

func (q *Queries) ListReleasesForUser(ctx context.Context, arg ListReleasesForUserParams) ([]ListReleasesForUserRow, error) {
	rows, err := q.db.Query(ctx, listReleasesForUser,
		arg.CreatedByUserID,
		arg.Cluster,
		arg.Namespace,
		arg.Template,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReleasesForUserRow
	for rows.Next() {
		var i ListReleasesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TemplateVersionID,
			&i.ClusterID,
			&i.Namespace,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClusterName,
			&i.TemplateName,
			&i.TemplateVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReleaseValuesAndVersion = `-- name: UpdateReleaseValuesAndVersion :exec
UPDATE releases
   SET template_version_id = $2,
       values_json = $3,
       rendered_yaml = $4,
       updated_at = NOW()
 WHERE id = $1
`

type UpdateReleaseValuesAndVersionParams struct {
	ID                pgtype.UUID     `json:"id"`
	TemplateVersionID pgtype.UUID     `json:"template_version_id"`
	ValuesJson        json.RawMessage `json:"values_json"`
	RenderedYaml      string          `json:"rendered_yaml"`
}

func (q *Queries) UpdateReleaseValuesAndVersion(ctx context.Context, arg UpdateReleaseValuesAndVersionParams) error {
	_, err := q.db.Exec(ctx, updateReleaseValuesAndVersion,
		arg.ID,
		arg.TemplateVersionID,
		arg.ValuesJson,
		arg.RenderedYaml,
	)
	return err
}
