// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, id_token_encrypted, refresh_token_encrypted, id_token_exp, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, id_token_encrypted, refresh_token_encrypted, id_token_exp, created_at, expires_at, provider
`

type CreateSessionParams struct {
	UserID                pgtype.UUID        `json:"user_id"`
	IDTokenEncrypted      string             `json:"id_token_encrypted"`
	RefreshTokenEncrypted pgtype.Text        `json:"refresh_token_encrypted"`
	IDTokenExp            pgtype.Timestamptz `json:"id_token_exp"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.IDTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.IDTokenExp,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IDTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.IDTokenExp,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Provider,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
WITH doomed AS (
  SELECT id FROM sessions
   WHERE expires_at < now()
   ORDER BY expires_at
   LIMIT $1
   FOR UPDATE SKIP LOCKED
)
DELETE FROM sessions WHERE id IN (SELECT id FROM doomed)
`

// Retention: an expired session is already unusable (GetSession filters on
// expires_at), so the row is nothing but an encrypted id_token and refresh
// token we no longer need. Sweep them instead of keeping them forever — the
// s_expires_at index makes this cheap. Deletes in bounded batches so one call
// can never hold a long lock on a table that logins are writing to.
//
// ORDER BY + FOR UPDATE SKIP LOCKED makes concurrent sweepers actually safe
// rather than merely idempotent: two replicas take disjoint batches in the
// same order instead of racing for the same rows, so neither deadlocks and
// neither comes back short while work remains (which the caller reads as
// "nothing left" and would otherwise end the pass early).
// The batch must be a CTE, not an IN (SELECT ... LIMIT). Postgres plans the
// latter as a semi-join and re-executes the subquery per outer row; with
// SKIP LOCKED each re-execution returns a *different* row, so the DELETE
// removes more than batch_size (EXPLAIN shows Nested Loop Semi Join over the
// Limit node). A CTE carrying a locking clause is never inlined, so it is
// evaluated exactly once.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, id_token_encrypted, refresh_token_encrypted, id_token_exp, created_at, expires_at, provider FROM sessions WHERE id = $1 AND expires_at > now()
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IDTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.IDTokenExp,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Provider,
	)
	return i, err
}

const updateSessionTokens = `-- name: UpdateSessionTokens :exec
UPDATE sessions
   SET id_token_encrypted = $2, refresh_token_encrypted = $3, id_token_exp = $4
 WHERE id = $1
`

type UpdateSessionTokensParams struct {
	ID                    pgtype.UUID        `json:"id"`
	IDTokenEncrypted      string             `json:"id_token_encrypted"`
	RefreshTokenEncrypted pgtype.Text        `json:"refresh_token_encrypted"`
	IDTokenExp            pgtype.Timestamptz `json:"id_token_exp"`
}

func (q *Queries) UpdateSessionTokens(ctx context.Context, arg UpdateSessionTokensParams) error {
	_, err := q.db.Exec(ctx, updateSessionTokens,
		arg.ID,
		arg.IDTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.IDTokenExp,
	)
	return err
}
