{{- if .Values.dex.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeport.dex.fullname" . }}
  labels:
    {{- include "kubeport.labels" . | nindent 4 }}
    app.kubernetes.io/component: dex
type: Opaque
stringData:
  DEX_CLIENT_SECRET: {{ required "dex.clientSecret is required when dex.enabled=true" .Values.dex.clientSecret | quote }}
{{- end -}}
