{{- if .Values.dex.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeport.dex.fullname" . }}
  labels:
    {{- include "kubeport.labels" . | nindent 4 }}
    app.kubernetes.io/component: dex
spec:
  type: ClusterIP
  selector:
    {{- include "kubeport.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dex
  ports:
    - name: http
      port: 5556
      targetPort: http
      protocol: TCP
{{- end -}}
