{{- if .Values.auth.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeport.auth.secretName" . }}
  labels:
    {{- include "kubeport.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "kubeport.databaseUrl" . | quote }}
  APP_ENCRYPTION_KEY_B64: {{ required "auth.appEncryptionKeyB64 is required when auth.create=true" .Values.auth.appEncryptionKeyB64 | quote }}
  OIDC_CLIENT_SECRET: {{ required "auth.oidcClientSecret is required when auth.create=true" .Values.auth.oidcClientSecret | quote }}
  {{- if .Values.dex.enabled }}
  DEMO_OIDC_CLIENT_SECRET: {{ required "dex.clientSecret is required when dex.enabled=true" .Values.dex.clientSecret | quote }}
  {{- end }}
{{- end -}}
